### ISSUE TITLE
Playlist crash when clicking - button.

### ISSUE THREAD

**Issue by Meowchestra** [parulina/bardmusicplayer#101]
* BardMusicPlayer BETA Version: 2.0.0.0

BMP crash scenario when using playlists.

1. Create a playlist with ``New``
2. Name it anything, i.e. ``p``
3. Click the ``+`` symbol and add a ``.mid``
4. Click ``...`` to go back to the playlist menu
5. Click ``-``.
6. Get brought back inside the playlist song list without navigating there.
7. Double click on the added ``.mid`` to try and load it.
8. Crash.

**Comment by GiR-Zippo** [comment]
Fixed with the next release
