### ISSUE TITLE
Unable to delete a playlist before entering it.

### ISSUE THREAD

**Issue by Meowchestra** [parulina/bardmusicplayer#102]
* BardMusicPlayer BETA Version: 2.0.0.0

You are unable to delete a playlist until you navigate into it.

1. Have a saved playlist from a previous session.
2. Highlight the playlist.
3. Click the ``X`` to try and delete it.
4. Doesn't delete.
5. Navigate into the playlist.
6. Navigate out of the playlist with ``...``.
7. Highlight the playlist.
8. Click the ``X`` to try and delete it.
9. Works now.

**Comment by GiR-Zippo** [comment]
Fixed with the next release
