### ISSUE TITLE
No note heatmap for local orchestra performers.

### ISSUE THREAD

**Issue by Meowchestra** [parulina/bardmusicplayer#105]
* BardMusicPlayer BETA Version: 2.0.0.0

Old 1.x BMP had a note heatmap on every hooked performer for the track they were playing on. Currently 2.x BMP no longer has this. Would it be possible to bring this back so you can better visualize octave shifts on individual tracks to see if adjustments need to be made in the midi?

**Comment by GiR-Zippo** [comment]
Unfortunately I haven't planed to bring this one back, atm.

**Comment by Meowchestra** [comment]
Not in scope of current UI goals so closing. Track heatmap would probably be better suited for a midi editor utility.
