### ISSUE TITLE
Crash when using the Post SongTitle button.

### ISSUE THREAD

**Issue by Meowchestra** [parulina/bardmusicplayer#123]
* BardMusicPlayer BETA Version: 2.0.0.1
* 8 local performers

Clicking on the ``Post Songtitle`` button inside the Performers options (double clicking a performer) causes BMP to crash. Tested both not changing anything (empty default box options) & changing to a specific channel (say).

![link](https://i.imgur.com/GLNyc6M.png)

**Comment by GiR-Zippo** [comment]
Can't confirm... atm.

**Comment by Meowchestra** [comment]
Are you testing with multiple attached performers? I only tested with 8 attached, not solo (1 client). Clicking the button always crashes BMP for me, also in 2.0.0.2.

**Comment by dmportella** [comment]
i can confirm this happens to me too on version 2.0.0.5 - solo bard

**Comment by ThymmRayne** [comment]
2.0.0.5 is outdated ---> 2.0.0.6 is the current version

**Comment by dmportella** [comment]
i will try that ty

**Comment by Meowchestra** [comment]
This is caused specifically when hitting the button _before_ loading any song.
