### ISSUE TITLE
Autopost channels prefix a number before the message in legacy mode.

### ISSUE THREAD

**Issue by Meowchestra** [parulina/bardmusicplayer#124]
* BardMusicPlayer BETA Version: 2.0.0.1

``say`` prefixes the number ``10``
``yell`` prefixes with the number ``30``
``shout`` prefixes with the number ``11``

It doesn't say the message in _any_ of the channels when you load a song. It uses what you have your client set to as default currently. For example all 3 messages can be said in party chat.

![link](https://i.imgur.com/RfGPLvu.png)
![link2](https://i.imgur.com/rbOnQYj.png)

---

With Hypnotoad v0.0.0.3, autopost on ``Dalamud`` and the 3 various channels seem to work fine.

**Comment by GiR-Zippo** [comment]
Whoops, my fault. Legacy mode will be fixed with the next version.
