### ISSUE TITLE
[Chat] All tab does not receive all chat channels from every local performer.

### ISSUE THREAD

**Issue by Meowchestra** [parulina/bardmusicplayer#125]
* BardMusicPlayer BETA Version: 2.0.0.1
* 8 local performers

While I personally do not care about this, I did notice the ``[Chat] All`` tab does not receive and output chat from Say, Tell, Yell, Shout, Alliance, Free Company (probably, couldn't test this one), CWLS, LS, or Echo from every client. If you have bards in different locations, it does not receive all messages.

This is especially important if it decides to use your bard alt for receiving messages instead of your main because this means you won't be able to see messages from FC / LS / CWLS you are in or tells you may get. Possible to use the performer assigned as ``Host`` for message receiving? Or go back to receiving from every client but would need to add a filter to prevent duplicate messages.

_Funny enough it did pick up battle text for using sprint though._

**Comment by GiR-Zippo** [comment]
Yes, it only receives the text from the host bard.
If I recall you mentioned this on the first BMP2.0-Test we did, that the chatbox will get messy. After this I changed it :)
Shall I change change it, to detect if the bard X isn't in your location to let the msg go through?
(this will take some time for me to make this happen)

**Comment by Meowchestra** [comment]
> Yes, it only receives the text from the host bard.

This doesn't seem to be the case for me. It was stuck using one of my bards in a housing ward despite my main being chosen as host. Not initially when opening BMP but afterwards selected the box. I wasn't receiving any logs from my main. If it is suppose to receive from host, maybe the switch isn't working.

> detect if the bard X isn't in your location to let the msg go through

This could work but I feel like it may become problematic and messy over time. How would you determine location? By zone matching? What about say chat in huge zones if you are on the other side of the map and aren't close enough? 

> mentioned this on the first BMP2.0-Test we did

The problem before was duplicate messages fed through based on the amount of attached clients. So if you had 8 clients receiving messages, 1 say chat would appear 8 times. If messages from all performers were brought back, there would need to be some filter added to prevent duplicate reporting.

**Comment by Meowchestra** [comment]
Chat is being removed.
