### ISSUE TITLE
Crash when setting XIV Affinity

### ISSUE THREAD

**Issue by Meowchestra** [parulina/bardmusicplayer#127]
* BardMusicPlayer BETA Version: 2.0.0.1

1. Open XIV Affinity on a Performer.
2. Click the ``Clear`` button.
3. Checkmark the first 4 boxes and click ``Set``. 
4. Affinity has been set to 4 threads on that Performer.

Now when you open up XIV Affinity again on that same performer;

1. Open XIV Affinity on the same Performer.
2. Click the ``Reset`` Button.
3. Click ``Set``.
4. Crash.
5. Go back to XIV Affinity.
6. Click ``Clear``. 
7. Click ``Set``.
8. Crash.
9. Go back to XIV Affinity.
10. Manually check the boxes of all available threads (32 in my case)
11. Click ``Set``.
12. Crash.

I can checkmark up to ``CPU31`` without it crashing. If ``CPU32``  is checkmarked, it crashes on ``Set``. Could it be because if all processor threads are selected in Windows (task manager), it _should_ also checkmark the first option ``<All Processors>`` which BMP isn't doing?

Windows 11 & AMD 3950X

**Comment by GiR-Zippo** [comment]
Can confirm the `Clear ` - `Set` bug.
Fixed with the next release.
