### ISSUE TITLE
Song Preview buzzing sound after song ends and runaway CPU usage.

### ISSUE THREAD

**Issue by Meowchestra** [parulina/bardmusicplayer#130]
* BardMusicPlayer BETA Version: 2.0.0.2

A high pitched buzzing constantly plays once the ``Song Preview`` stops playing from reaching end of duration. This seems to happen when a held note is being played when the end is reached. You have to click ``Stop`` to make it go away. CPU usage of BMP during this buzzing continues to climb. I stopped it at ~30%.

Attached is a midi that breaks every time when the end is reached.
[1.zip](https://github.com/BardMusicPlayer/BardMusicPlayer/files/9397663/1.zip)

**Comment by Meowchestra** [comment]
Here is a video showing the problem, as well as an additional problem of BMP buzzing if the song ends being held and remains buzzing even after closing BMP. Living in task manager.

https://user-images.githubusercontent.com/42126400/186069778-aa1ffbe4-7cf0-455b-8b64-d71ada5cecb0.mp4

**Comment by GiR-Zippo** [comment]
Fixed with the next version
