### ISSUE TITLE
Crash when loading non-supported files in Song Preview.

### ISSUE THREAD

**Issue by Meowchestra** [parulina/bardmusicplayer#138]
* BardMusicPlayer BETA Version: 2.0.0.2

BMP crashes if you load files that are not a .mid or .mmsong into the ``Song Preview``.

1. Go to Performers.
2.  Navigate to the ``...`` button, ``Save Performer Setting``, and name it anything.
3. Go to ``Song Preview``.
4. Click ``Load``.
5. At the bottom of explorer, change ``MIDI file`` to ``All files (*.*)``.
6. Load the new saved performer settings .cfg file.
7. Poof. Crash.

Should restrict it so you can only load mid and mmsong files as you seem to be able to load anything.

**Comment by GiR-Zippo** [comment]
Jep, my fault.
Fixed with the next version.
(Is it enough, to just remove the `*.*`, or do we need some checks too, if someone overrides this?)
