### ISSUE TITLE
Playlist export is not saving as a JSON file.

### ISSUE THREAD

**Issue by Meowchestra** [parulina/bardmusicplayer#139]
* BardMusicPlayer BETA Version: 2.0.0.2

Using the playlist export option, the file does not save in JSON like the option implies. It exports as a ``.plz`` formatted file which isn't human readable in notepad.

![link](https://i.imgur.com/ir4abyM.png)
![link2](https://i.imgur.com/Bh0Perm.png)

**Comment by GiR-Zippo** [comment]
Yep, this is a compressed Json file with the current playlist and all songdata inside. It's for exchanging a specific playlist from your Catalog to other ppl.
That's why I called it PLZ (Playlist Zip).

**Comment by Meowchestra** [comment]
Should the options just be generically called Import & Export Playlist then? Since it isn't necessarily basic json and most people don't need to know what it is exporting as.

**Comment by GiR-Zippo** [comment]
Sure, will be renamed at the next version.
