### ISSUE TITLE
You are able to import a playlist into the playlist directory, which causes a crash.

### ISSUE THREAD

**Issue by Meowchestra** [parulina/bardmusicplayer#140]
* BardMusicPlayer BETA Version: 2.0.0.2

You are able to import a playlist into the playlist directory, which causes a crash.

1. Create a new playlist and name it anything.
2. Add a song to the playlist so it doesn't disappear if you go back.
3. Navigate back to the playlist selection parent directory.
4. Click ``Import Playlist from Json`` button.
5. Import your previously saved playlist.
6. Playlist is outputted in what looks like the new playlist.
7. Can't go back to playlist directory & clicking any song to load causes a crash.

This also happens if you _delete_ a playlist so none exist and then try importing. The songs have nowhere to go and crash when loaded.

I should also note that normally you can't import a playlist unless you enter one once. The buttons do nothing which seems counter-intuitive. It may be better if the entire playlist category / name itself is saved so you can import entire sections from the root directory and have a separate option if you want to merge files into an existing playlists.

**Comment by GiR-Zippo** [comment]
Oh, that's neat.
Fixed with the next update.
