### ISSUE TITLE
New playlist name box has no size restriction in UI & crashes if too long.

### ISSUE THREAD

**Issue by Meowchestra** [parulina/bardmusicplayer#141]
* BardMusicPlayer BETA Version: 2.0.0.2

The naming box for new playlists has no bounding box size restriction so it expands indefinitely. Likewise if you hit enter after typing an extremely long name, BMP crashes.

![link](https://i.imgur.com/MUCKGkS.png)

**Comment by Meowchestra** [comment]
This also happens with the search box but that doesn't crash.

![link](https://i.imgur.com/YKOvQFM.png)

**Comment by GiR-Zippo** [comment]
Fixed with the next version.
The playlist is now limited to 42 chars (might be enough) and the search is limited to 80 chars (window will expand)
