### ISSUE TITLE
Track selection

### ISSUE THREAD

**Issue by postcards114** [parulina/bardmusicplayer#146]
V2.0.0.5 - When using an Octet, and choosing a song that is only 6 tracks (probably less too), you are no longer able to adjust the T8 to anything else (Assuming this applies to any track that would have to "scroll through" an empty track).  This seems to be because T7 is an empty track and will not let you scroll through empty tracks.  T7 can be reassigned up but cannot scroll down to T8 (makes sense for T7).  This doesn't allow whoever is "assigned" to T8 to swap to another track.  Cannot even type T6 T4, etc etc into the box to force it to swap.

**Comment by Meowchestra** [comment]
https://github.com/BardMusicPlayer/BardMusicPlayer/issues/121

**Comment by Meowchestra** [comment]
Closing since there is already an open issue for this.
