### ISSUE TITLE
Auto-equip failing to hit correct keybind with modifiers

### ISSUE THREAD

**Issue by flop-sy** [parulina/bardmusicplayer#157]
Version: BardMusicPlayer-BETA-2.0.0.6

When picking a song while auto-equip is enabled it sends the keybind input to pull out that instrument two times, While the bards still have their instruments out when you pick a new song it will sometimes hit the correct keybind but without the modifier to pull out that instrument. For example:

1. Saxophone is keybind `shift+5`
2. Violin is keybind `5`
4. Loading a song while the bards are still holding instruments that contains Saxophone
5. Auto-equip sends keybind `5` and then `shift+5` rather than sending `shift+5` twice.

Not sure if the two inputs for auto-equip is intentional.

**Comment by flop-sy** [comment]
Update: Had both Auto Equip solo Bard & Auto Equip Orchestra enabled while doing this, they both still function and attempt to send an input each causing it to sometimes not hit the modifier, happens about 50% of the time.

Disabling one of these options makes it only send a single input.

**Comment by Meowchestra** [comment]
Individual auto equip settings are being merged into one AutoEquip Performer(s) setting so this issue could probably be closed by https://github.com/BardMusicPlayer/BardMusicPlayer/pull/145.
