### ISSUE TITLE
Check whether BMP conforms to most common "flaws" produced by editing tools

### ISSUE THREAD

**Issue by parulina** [parulina/bardmusicplayer#16]
As title. Fruity loops, Midieditor, sibelius, etc.
- Some of these editors don't allow changing track names.
- Some of these editors do strange stuff to midis.

**Comment by MoogleTroupe** [comment]
the scrubber now checks for program change numbers used by sibelius. however it does not set the "correct" octave of said program numbers that you would expect from sibelius. i'm unsure if that is a good idea to do so.
