### ISSUE TITLE
Missing reference in latest version

### ISSUE THREAD

**Issue by dmportella** [parulina/bardmusicplayer#330]
Hello again

I got latest recently (today) and eeeee PartyLeader Event is missing there is no file in the seer project for, currently develop is breaking and there is some other issues with performer references in some xaml file that it wont build any help possible?

OR what version should I be building from??

https://github.com/BardMusicPlayer/BardMusicPlayer/blame/75cd244620d62efcab54d9eee2ef608e9a9456d0/BardMusicPlayer.Seer/Reader/Backend/Machina/Packet.3704.cs#L71

**Comment by GiR-Blunti** [comment]
Sorry, my fault while copying the files over. The BMP2.x doesn't care about the PartyLeader.
https://github.com/BardMusicPlayer/BardMusicPlayer/pull/331

**Comment by dmportella** [comment]
> Sorry, my fault while copying the files over. The BMP2.x doesn't care about the PartyLeader. #331

yeah no problem ty @GiR-Blunti
