### ISSUE TITLE
Latest website release fails to create windows

### ISSUE THREAD

**Issue by ChristopherJTrent** [parulina/bardmusicplayer#38]
When using the executable for 1.24 that can be downloaded from bmp.sqnya.se, no windows are created, no error messages are shown, and no log files are created. The program quietly dies moments after being started.

I checked out and built the source code,  and this issue has been remedied as of current master, but an updated EXE should probably be released.

**Comment by ChristopherJTrent** [comment]
Nuked my Appdata/Local/FFBardMusicPlayer directory, which has remedied the problem for now.

Issue originally started when replacing my Motherboard and Processor, moving from Intel to AMD. 
Are there any values in any of the user.config files that might be platform specific?

**Comment by parulina** [comment]
Do you have a back up of the folder?
