### ISSUE TITLE
Program locks up on file browser close when songs directory is large

### ISSUE THREAD

**Issue by Arkevorkhat** [parulina/bardmusicplayer#40]
Steps to reproduce:
1) have a songs directory with a very large number of files (mine contains about 2,300)
2) change the current song using the file browser (double click the file)
3) note that BMP takes a decent period of time to begin responding again.

I spoke with Hopper ([Levi] Chipotle Ismylife on the discord) and they said that they have a fix in the pipeline, but it hasn't been pushed either to the 1.24 updates branch, nor an available release. (Full disclosure: I was given a patch file from their working directory, but the changes therein didn't remedy the above issue.)

**Comment by trotlinebeercan** [comment]
correct. the patch was only one issue of the two i've found. a fix will be pushed soon.

thanks for reporting the issue

**Comment by trotlinebeercan** [comment]
pushed to master, cherry-picked onto 1.24-updates. let me know if you still have problems from the 1.24 branch.

**Comment by Arkevorkhat** [comment]
I'll pull that down and give it a shot.
