### ISSUE TITLE
[1.27] Songexplorer put players back to the top

### ISSUE THREAD

**Issue by GiR-Zippo** [parulina/bardmusicplayer#67]
_-some users when trying to select a new song, are instead put back to the top of their song list_
Related to: https://github.com/BardMusicPlayer/BardMusicPlayer/commit/15361fef21ab64d53a640592d2587f2935934400

If the intension was to remove the text in the search bar after open the file browser, this patch should work and fix the problems some players are experiencing.

[Songexplorer-patch.txt](https://github.com/BardMusicPlayer/BardMusicPlayer/files/6572102/Songexplorer-patch.txt)

**Comment by trotlinebeercan** [comment]
it fixes the track toggle causing the song to reset, but reintroduces the bug with midi searching.

looking into it now.

**Comment by trotlinebeercan** [comment]
fixed in 7d22a14693b6989bec1bd66aa263ae20e8abdc97
