### ISSUE TITLE
Failing to load MIDI files

### ISSUE THREAD

**Issue by NordicSnow** [parulina/bardmusicplayer#79]
![image](https://user-images.githubusercontent.com/33619302/125733446-2fc4df21-93f3-458b-80cf-0247f1bb8301.png)

Opening certain midi files causes an error saying it cannot be loaded and that more than one error has occurred.

Version 1.4
Windows 11 21H2

**Comment by BSoD38** [comment]
I have the same issue. I have rolled back to version 1.27 until this problem is solved.

**Comment by tigurand** [comment]
Same here. 1.27 is working fine.

**Comment by Clocktown** [comment]
Same issue - additionally, if I click on one of the tabs (settings, chat all etc.) this always takes me back to the song selection screen afterwards, so I have to restart the software to use it properly.

**Comment by JarrettFritz** [comment]
Are the midi tracks named? BMP will only play tracks if they are named.

**Comment by troy-f** [comment]
The tracks are loaded is changing in 2.0. Please check it out when it's released!
