### ISSUE TITLE
Unhandled exception when using typing to search for midi

### ISSUE THREAD

**Issue by Arcadia64** [parulina/bardmusicplayer#80]
If you type to search for a song but there is no match, an unhandled exception is thrown.
![bmp_144_exception](https://user-images.githubusercontent.com/25129231/126568002-a30f8dad-d590-4fba-9fde-408ca918a7c9.png)
[bmp_144_exception_details.txt](https://github.com/BardMusicPlayer/BardMusicPlayer/files/6859114/bmp_144_exception_details.txt)

**Comment by tancred423** [comment]
Same issue on my side
[dump.txt](https://github.com/BardMusicPlayer/BardMusicPlayer/files/6995780/dump.txt)

**Comment by darmanilink** [comment]
Occurring for me as well
