### ISSUE TITLE
Fails to start under Wine: inputLanguage is not recognized by the system

### ISSUE THREAD

**Issue by Maia-Everett** [parulina/bardmusicplayer#82]
BMP works fine under Windows, but under Wine with `winetricks dotnet48` installed, it fails to start with this .NET stacktrace:

```
05d8:fixme:keyboard:ActivateKeyboardLayout HKL_NEXT and HKL_PREV not supported
...
Unhandled Exception: System.ArgumentException: inputLanguage is not recognized by the system.
Parameter name: value
   at System.Windows.Forms.InputLanguage.set_CurrentInputLanguage(InputLanguage value)
   at System.Windows.Forms.Application.set_CurrentInputLanguage(InputLanguage value)
   at FFBardMusicPlayer.Program.Main(String[] args)
```

This seems like a bug in Wine, with .NET trying to cycle through keyboard layouts, which Wine doesn't support. Admittedly I'm not sure if BMP would start under Wine even if a workaround for this was added.

**Comment by GiR-Zippo** [comment]
This is a bug related to wine. You can implement a workaround to get the keyboard input fixed to your country, but if the BMP-Team does this, we have to release for every country a different version.

The reason why such bugs appearing is: .net was created from Microsoft to make programming things in Windows easier, Wine gives Windows programs an API translation to the underlaying *nix system, but unfortunately some calls are not implemented. 
But don't get confused with .net and .net core/mono, the core version runs mostly native on *nix systems and differs from the og .net.
A blast from the past: Programming platform independend in the old days we used C++ in conjunction with QT, GTK+ (like Firefox and Gimp do) or most likely Java.

**Comment by trotlinebeercan** [comment]
We're not officially supporting Wine any time soon.

**Comment by Maia-Everett** [comment]
The good news is that with the keyboard layout code commented out, BMP starts and works under Wine. In case another Wine user has the same problem, here's a build of BMP that runs under Wine. You might also need to enable "Force playback" in settings.

[bmp-wine.zip](https://github.com/BardMusicPlayer/BardMusicPlayer/files/7718212/bmp-wine.zip)
