### ISSUE TITLE
MIDI input not working in 1.4

### ISSUE THREAD

**Issue by obfuscoder** [parulina/bardmusicplayer#84]
With version 1.4 the MIDI input is not working. In the previous version 1.27 it worked fine.

**Comment by Peskier** [comment]
I was planning to raise the same issue but for me, checking the Force Playback option solved it. With that option on, my digital piano inputs went through to the game as expected.

**Comment by Braste** [comment]
Using force playback did not help.

**Comment by troy-f** [comment]
MIDI input is being deprecated in 2.0. Try out NetHarmony by RiscoRabbit, it is an app dedicated to MIDI input -> ffxiv, including party support, and should have an english translation sooner or later.
