### ISSUE TITLE
Question: Contributing

### ISSUE THREAD

**Issue by las3r** [parulina/bardmusicplayer#85]
Hi there,

I am looking to contribute to this project as I'm a vivid user of the BMP myself. Since there is no contributing file I was wondering:
- Do you accept pull requests?
- What is the way of working with these? 
- can you add a CONTRIB file describing this?

I really want to help and work on the player and I'd like to discuss what I can do to help.

**Comment by troy-f** [comment]
a CONTRIB doc will be created after the relase of 2.0-alpha1 which is coming next month.
