### ISSUE TITLE
Song Preview breaks when the song reaches the end of the duration.

### ISSUE THREAD

**Issue by Meowchestra** [parulina/bardmusicplayer#91]
* BardMusicPlayer BETA Version: 2.0.0.0

Using the ``Song Preview``, when a loaded song reaches the end of the duration and stops forcefully, you cannot play the song again. Nor can you load a different song and play it by clicking ``Play`` or ``Stop``.

If you never reach the end of the track, you can use the ``Play``, ``Stop``, and ``Load`` buttons without issue playing back various songs.

**Comment by GiR-Zippo** [comment]
Fixed with the next release
