### ISSUE TITLE
MIDI Input device box stretches outside default UI window size.

### ISSUE THREAD

**Issue by Meowchestra** [parulina/bardmusicplayer#97]
* BardMusicPlayer BETA Version: 2.0.0.0

The MIDI Input device box stretches outside default UI window size. You have to expand the BMP window to see where it ends. I assume it is padded for some long device name or something?

![link](https://i.imgur.com/KBB2gK6.png)

![link2](https://i.imgur.com/kNGaauL.png)

**Comment by Meowchestra** [comment]
Another box that is slightly cut off in the default size. The individual performer settings menu when double clicking on a performer.

![link](https://i.imgur.com/85LF1Ka.png)

**Comment by GiR-Zippo** [comment]
Fixed by the next version
