### ISSUE TITLE
Statistics missing beats per minute & note per second information.

### ISSUE THREAD

**Issue by Meowchestra** [parulina/bardmusicplayer#98]
* BardMusicPlayer BETA Version: 2.0.0.0

The statistics tab is missing the ``Beats per minute`` & ``Note per second`` information.

![link](https://i.imgur.com/ntAu5B8.png)

**Comment by GiR-Zippo** [comment]
Will be removed in the next release, since it doesn't make any sense to keep it. The default squencer bpm is 160 and all songs will be converted into this raster (like the old BMP does).
